//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.24 at 07:56:15 PM BRT 
//

@XmlSchema(
		namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, 
		xmlns={ @XmlNs(prefix="imscp", namespaceURI="http://www.imsglobal.org/xsd/imscp_v1p1"),
				@XmlNs(prefix="imsld", namespaceURI="http://www.imsglobal.org/xsd/imsld_v1p0"),
		})
package org.imsglobal.jaxb.content;
import javax.xml.bind.annotation.*;

