//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for activitiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="activitiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}learning-activity"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}support-activity"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}activity-structure"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "activitiesType", propOrder = {
		"learningActivityOrSupportActivityOrActivityStructure"
})
public class Activities extends ImeObject
implements Serializable
{

	private final static long serialVersionUID = 12345L;
	@XmlElements({
		@XmlElement(name = "activity-structure", type = ActivityStructure.class),
		@XmlElement(name = "learning-activity", type = LearningActivity.class),
		@XmlElement(name = "support-activity", type = SupportActivity.class)
	})
	protected List<Serializable> learningActivityOrSupportActivityOrActivityStructure;

	/**
	 * Gets the value of the learningActivityOrSupportActivityOrActivityStructure property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the learningActivityOrSupportActivityOrActivityStructure property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getLearningActivityOrSupportActivityOrActivityStructure().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ActivityStructure }
	 * {@link LearningActivity }
	 * {@link SupportActivity }
	 * 
	 * 
	 */
	public List<Serializable> getLearningActivityOrSupportActivityOrActivityStructure() {
		if (learningActivityOrSupportActivityOrActivityStructure == null) {
			learningActivityOrSupportActivityOrActivityStructure = new ArrayList<Serializable>();
		}
		return this.learningActivityOrSupportActivityOrActivityStructure;
	}

	@Override
	public void validateImsLd() {
		clearStructureOfValidationMessages();

		if (getLearningActivityOrSupportActivityOrActivityStructure().size() == 0)
			putERROR("*Deve existir ao menos uma atividade registrada...");
		else
			for (Serializable imeO: getLearningActivityOrSupportActivityOrActivityStructure()) {
				((ImeObject)imeO).validateImsLd();
				putERRORs(((ImeObject)imeO).getERRORs());
				putWARNINGs(((ImeObject)imeO).getWARNINGs());
			}

	}

}
