//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for calculateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="calculateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.imsglobal.org/xsd/imsld_v1p0}grp.calculate"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calculateType", propOrder = {
    "grpOperand"
})
public class Calculate extends ImeObject
    implements Serializable
{

    private final static long serialVersionUID = 12345L;
    @XmlElementRefs({
        @XmlElementRef(name = "property-value", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "time-unit-of-learning-started", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = TimeUnitOfLearningStarted.class),
        @XmlElementRef(name = "is-member-of-role", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = IsMemberOfRole.class),
        @XmlElementRef(name = "not", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "and", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "current-datetime", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = CurrentDatetime.class),
        @XmlElementRef(name = "divide", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "datetime-activity-started", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = DatetimeActivityStarted.class),
        @XmlElementRef(name = "subtract", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "greater-than", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "users-in-role", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "or", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "sum", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "is", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "less-than", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "no-value", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "is-not", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "property-ref", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = PropertyRef.class),
        @XmlElementRef(name = "multiply", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "complete", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class)
    })
    protected List<Object> grpOperand;

    /**
     * Gets the value of the grpOperand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grpOperand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrpOperand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link PropertyValue }{@code >}
     * {@link TimeUnitOfLearningStarted }
     * {@link IsMemberOfRole }
     * {@link JAXBElement }{@code <}{@link Expression }{@code >}
     * {@link JAXBElement }{@code <}{@link Operator }{@code >}
     * {@link CurrentDatetime }
     * {@link JAXBElement }{@code <}{@link Calculate }{@code >}
     * {@link JAXBElement }{@code <}{@link Calculate }{@code >}
     * {@link DatetimeActivityStarted }
     * {@link JAXBElement }{@code <}{@link Operator }{@code >}
     * {@link JAXBElement }{@code <}{@link UsersInRole }{@code >}
     * {@link JAXBElement }{@code <}{@link Calculate }{@code >}
     * {@link JAXBElement }{@code <}{@link Sum }{@code >}
     * {@link JAXBElement }{@code <}{@link Calculate }{@code >}
     * {@link PropertyRef }
     * {@link JAXBElement }{@code <}{@link Calculate }{@code >}
     * {@link JAXBElement }{@code <}{@link NoValue }{@code >}
     * {@link JAXBElement }{@code <}{@link Calculate }{@code >}
     * {@link JAXBElement }{@code <}{@link Complete }{@code >}
     * {@link JAXBElement }{@code <}{@link Calculate }{@code >}
     * 
     * 
     */
    public List<Object> getGrpOperand() {
        if (grpOperand == null) {
            grpOperand = new ArrayList<Object>();
        }
        return this.grpOperand;
    }

	@Override
	public void validateImsLd() {
		// TODO Auto-generated method stub
		
	}

}
