//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for completeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="completeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}learning-activity-ref"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}support-activity-ref"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}unit-of-learning-href"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}activity-structure-ref"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}role-part-ref"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}act-ref"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}play-ref"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "completeType", propOrder = {
    "learningActivityRef",
    "supportActivityRef",
    "unitOfLearningHref",
    "activityStructureRef",
    "rolePartRef",
    "actRef",
    "playRef"
})
public class Complete extends ImeObject
    implements Serializable
{

    private final static long serialVersionUID = 12345L;
    @XmlElement(name = "learning-activity-ref")
    protected LearningActivityRef learningActivityRef;
    @XmlElement(name = "support-activity-ref")
    protected SupportActivityRef supportActivityRef;
    @XmlElement(name = "unit-of-learning-href")
    protected UnitOfLearningHref unitOfLearningHref;
    @XmlElement(name = "activity-structure-ref")
    protected ActivityStructureRef activityStructureRef;
    @XmlElement(name = "role-part-ref")
    protected RolePartRef rolePartRef;
    @XmlElement(name = "act-ref")
    protected ActRef actRef;
    @XmlElement(name = "play-ref")
    protected PlayRef playRef;

    /**
     * Gets the value of the learningActivityRef property.
     * 
     * @return
     *     possible object is
     *     {@link LearningActivityRef }
     *     
     */
    public LearningActivityRef getLearningActivityRef() {
        return learningActivityRef;
    }

    /**
     * Sets the value of the learningActivityRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningActivityRef }
     *     
     */
    public void setLearningActivityRef(LearningActivityRef value) {
        this.learningActivityRef = value;
    }

    /**
     * Gets the value of the supportActivityRef property.
     * 
     * @return
     *     possible object is
     *     {@link SupportActivityRef }
     *     
     */
    public SupportActivityRef getSupportActivityRef() {
        return supportActivityRef;
    }

    /**
     * Sets the value of the supportActivityRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportActivityRef }
     *     
     */
    public void setSupportActivityRef(SupportActivityRef value) {
        this.supportActivityRef = value;
    }

    /**
     * Gets the value of the unitOfLearningHref property.
     * 
     * @return
     *     possible object is
     *     {@link UnitOfLearningHref }
     *     
     */
    public UnitOfLearningHref getUnitOfLearningHref() {
        return unitOfLearningHref;
    }

    /**
     * Sets the value of the unitOfLearningHref property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitOfLearningHref }
     *     
     */
    public void setUnitOfLearningHref(UnitOfLearningHref value) {
        this.unitOfLearningHref = value;
    }

    /**
     * Gets the value of the activityStructureRef property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityStructureRef }
     *     
     */
    public ActivityStructureRef getActivityStructureRef() {
        return activityStructureRef;
    }

    /**
     * Sets the value of the activityStructureRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityStructureRef }
     *     
     */
    public void setActivityStructureRef(ActivityStructureRef value) {
        this.activityStructureRef = value;
    }

    /**
     * Gets the value of the rolePartRef property.
     * 
     * @return
     *     possible object is
     *     {@link RolePartRef }
     *     
     */
    public RolePartRef getRolePartRef() {
        return rolePartRef;
    }

    /**
     * Sets the value of the rolePartRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link RolePartRef }
     *     
     */
    public void setRolePartRef(RolePartRef value) {
        this.rolePartRef = value;
    }

    /**
     * Gets the value of the actRef property.
     * 
     * @return
     *     possible object is
     *     {@link ActRef }
     *     
     */
    public ActRef getActRef() {
        return actRef;
    }

    /**
     * Sets the value of the actRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActRef }
     *     
     */
    public void setActRef(ActRef value) {
        this.actRef = value;
    }

    /**
     * Gets the value of the playRef property.
     * 
     * @return
     *     possible object is
     *     {@link PlayRef }
     *     
     */
    public PlayRef getPlayRef() {
        return playRef;
    }

    /**
     * Sets the value of the playRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayRef }
     *     
     */
    public void setPlayRef(PlayRef value) {
        this.playRef = value;
    }

	@Override
	public void validateImsLd() {
		// TODO Auto-generated method stub
		
	}

}
