//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for elseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="elseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;group ref="{http://www.imsglobal.org/xsd/imsld_v1p0}grp.then" maxOccurs="unbounded"/>
 *         &lt;group ref="{http://www.imsglobal.org/xsd/imsld_v1p0}grp.condition"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elseType", propOrder = {
    "grpThen",
    "_if",
    "then",
    "_else"
})
public class Else extends ImeObject implements Serializable
{

    private final static long serialVersionUID = 12345L;
    @XmlElementRefs({
        @XmlElementRef(name = "show", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "hide", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "notification", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "change-property-value", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> grpThen;
    @XmlElement(name = "if")
    protected Expression _if;
    protected Then then;
    @XmlElement(name = "else")
    protected Else _else;

    /**
     * Gets the value of the grpThen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grpThen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrpThen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Notification }{@code >}
     * {@link JAXBElement }{@code <}{@link ShowHide }{@code >}
     * {@link JAXBElement }{@code <}{@link ChangePropertyValue }{@code >}
     * {@link JAXBElement }{@code <}{@link ShowHide }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getGrpThen() {
        if (grpThen == null) {
            grpThen = new ArrayList<JAXBElement<?>>();
        }
        return this.grpThen;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setIf(Expression value) {
        this._if = value;
    }

    /**
     * Gets the value of the then property.
     * 
     * @return
     *     possible object is
     *     {@link Then }
     *     
     */
    public Then getThen() {
        return then;
    }

    /**
     * Sets the value of the then property.
     * 
     * @param value
     *     allowed object is
     *     {@link Then }
     *     
     */
    public void setThen(Then value) {
        this.then = value;
    }

    /**
     * Gets the value of the else property.
     * 
     * @return
     *     possible object is
     *     {@link Else }
     *     
     */
    public Else getElse() {
        return _else;
    }

    /**
     * Sets the value of the else property.
     * 
     * @param value
     *     allowed object is
     *     {@link Else }
     *     
     */
    public void setElse(Else value) {
        this._else = value;
    }

	@Override
	public void validateImsLd() {
		// TODO Auto-generated method stub
		
	}

}
