//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for expressionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expressionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.imsglobal.org/xsd/imsld_v1p0}grp.expression"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expressionType", propOrder = {
    "isMemberOfRole",
    "is",
    "isNot",
    "and",
    "or",
    "sum",
    "subtract",
    "multiply",
    "divide",
    "greaterThan",
    "lessThan",
    "usersInRole",
    "noValue",
    "timeUnitOfLearningStarted",
    "datetimeActivityStarted",
    "currentDatetime",
    "complete",
    "not"
})
public class Expression extends ImeObject implements Serializable
{

    private final static long serialVersionUID = 12345L;
    @XmlElement(name = "is-member-of-role")
    protected IsMemberOfRole isMemberOfRole;
    protected Calculate is;
    @XmlElement(name = "is-not")
    protected Calculate isNot;
    protected Operator and;
    protected Operator or;
    protected Sum sum;
    protected Calculate subtract;
    protected Calculate multiply;
    protected Calculate divide;
    @XmlElement(name = "greater-than")
    protected Calculate greaterThan;
    @XmlElement(name = "less-than")
    protected Calculate lessThan;
    @XmlElement(name = "users-in-role")
    protected UsersInRole usersInRole;
    @XmlElement(name = "no-value")
    protected NoValue noValue;
    @XmlElement(name = "time-unit-of-learning-started")
    protected TimeUnitOfLearningStarted timeUnitOfLearningStarted;
    @XmlElement(name = "datetime-activity-started")
    protected DatetimeActivityStarted datetimeActivityStarted;
    @XmlElement(name = "current-datetime")
    protected CurrentDatetime currentDatetime;
    protected Complete complete;
    protected Expression not;

    /**
     * Gets the value of the isMemberOfRole property.
     * 
     * @return
     *     possible object is
     *     {@link IsMemberOfRole }
     *     
     */
    public IsMemberOfRole getIsMemberOfRole() {
        return isMemberOfRole;
    }

    /**
     * Sets the value of the isMemberOfRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsMemberOfRole }
     *     
     */
    public void setIsMemberOfRole(IsMemberOfRole value) {
        this.isMemberOfRole = value;
    }

    /**
     * Gets the value of the is property.
     * 
     * @return
     *     possible object is
     *     {@link Calculate }
     *     
     */
    public Calculate getIs() {
        return is;
    }

    /**
     * Sets the value of the is property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calculate }
     *     
     */
    public void setIs(Calculate value) {
        this.is = value;
    }

    /**
     * Gets the value of the isNot property.
     * 
     * @return
     *     possible object is
     *     {@link Calculate }
     *     
     */
    public Calculate getIsNot() {
        return isNot;
    }

    /**
     * Sets the value of the isNot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calculate }
     *     
     */
    public void setIsNot(Calculate value) {
        this.isNot = value;
    }

    /**
     * Gets the value of the and property.
     * 
     * @return
     *     possible object is
     *     {@link Operator }
     *     
     */
    public Operator getAnd() {
        return and;
    }

    /**
     * Sets the value of the and property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operator }
     *     
     */
    public void setAnd(Operator value) {
        this.and = value;
    }

    /**
     * Gets the value of the or property.
     * 
     * @return
     *     possible object is
     *     {@link Operator }
     *     
     */
    public Operator getOr() {
        return or;
    }

    /**
     * Sets the value of the or property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operator }
     *     
     */
    public void setOr(Operator value) {
        this.or = value;
    }

    /**
     * Gets the value of the sum property.
     * 
     * @return
     *     possible object is
     *     {@link Sum }
     *     
     */
    public Sum getSum() {
        return sum;
    }

    /**
     * Sets the value of the sum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sum }
     *     
     */
    public void setSum(Sum value) {
        this.sum = value;
    }

    /**
     * Gets the value of the subtract property.
     * 
     * @return
     *     possible object is
     *     {@link Calculate }
     *     
     */
    public Calculate getSubtract() {
        return subtract;
    }

    /**
     * Sets the value of the subtract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calculate }
     *     
     */
    public void setSubtract(Calculate value) {
        this.subtract = value;
    }

    /**
     * Gets the value of the multiply property.
     * 
     * @return
     *     possible object is
     *     {@link Calculate }
     *     
     */
    public Calculate getMultiply() {
        return multiply;
    }

    /**
     * Sets the value of the multiply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calculate }
     *     
     */
    public void setMultiply(Calculate value) {
        this.multiply = value;
    }

    /**
     * Gets the value of the divide property.
     * 
     * @return
     *     possible object is
     *     {@link Calculate }
     *     
     */
    public Calculate getDivide() {
        return divide;
    }

    /**
     * Sets the value of the divide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calculate }
     *     
     */
    public void setDivide(Calculate value) {
        this.divide = value;
    }

    /**
     * Gets the value of the greaterThan property.
     * 
     * @return
     *     possible object is
     *     {@link Calculate }
     *     
     */
    public Calculate getGreaterThan() {
        return greaterThan;
    }

    /**
     * Sets the value of the greaterThan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calculate }
     *     
     */
    public void setGreaterThan(Calculate value) {
        this.greaterThan = value;
    }

    /**
     * Gets the value of the lessThan property.
     * 
     * @return
     *     possible object is
     *     {@link Calculate }
     *     
     */
    public Calculate getLessThan() {
        return lessThan;
    }

    /**
     * Sets the value of the lessThan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calculate }
     *     
     */
    public void setLessThan(Calculate value) {
        this.lessThan = value;
    }

    /**
     * Gets the value of the usersInRole property.
     * 
     * @return
     *     possible object is
     *     {@link UsersInRole }
     *     
     */
    public UsersInRole getUsersInRole() {
        return usersInRole;
    }

    /**
     * Sets the value of the usersInRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsersInRole }
     *     
     */
    public void setUsersInRole(UsersInRole value) {
        this.usersInRole = value;
    }

    /**
     * Gets the value of the noValue property.
     * 
     * @return
     *     possible object is
     *     {@link NoValue }
     *     
     */
    public NoValue getNoValue() {
        return noValue;
    }

    /**
     * Sets the value of the noValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoValue }
     *     
     */
    public void setNoValue(NoValue value) {
        this.noValue = value;
    }

    /**
     * Gets the value of the timeUnitOfLearningStarted property.
     * 
     * @return
     *     possible object is
     *     {@link TimeUnitOfLearningStarted }
     *     
     */
    public TimeUnitOfLearningStarted getTimeUnitOfLearningStarted() {
        return timeUnitOfLearningStarted;
    }

    /**
     * Sets the value of the timeUnitOfLearningStarted property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeUnitOfLearningStarted }
     *     
     */
    public void setTimeUnitOfLearningStarted(TimeUnitOfLearningStarted value) {
        this.timeUnitOfLearningStarted = value;
    }

    /**
     * Gets the value of the datetimeActivityStarted property.
     * 
     * @return
     *     possible object is
     *     {@link DatetimeActivityStarted }
     *     
     */
    public DatetimeActivityStarted getDatetimeActivityStarted() {
        return datetimeActivityStarted;
    }

    /**
     * Sets the value of the datetimeActivityStarted property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatetimeActivityStarted }
     *     
     */
    public void setDatetimeActivityStarted(DatetimeActivityStarted value) {
        this.datetimeActivityStarted = value;
    }

    /**
     * Gets the value of the currentDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentDatetime }
     *     
     */
    public CurrentDatetime getCurrentDatetime() {
        return currentDatetime;
    }

    /**
     * Sets the value of the currentDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentDatetime }
     *     
     */
    public void setCurrentDatetime(CurrentDatetime value) {
        this.currentDatetime = value;
    }

    /**
     * Gets the value of the complete property.
     * 
     * @return
     *     possible object is
     *     {@link Complete }
     *     
     */
    public Complete getComplete() {
        return complete;
    }

    /**
     * Sets the value of the complete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Complete }
     *     
     */
    public void setComplete(Complete value) {
        this.complete = value;
    }

    /**
     * Gets the value of the not property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getNot() {
        return not;
    }

    /**
     * Sets the value of the not property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setNot(Expression value) {
        this.not = value;
    }

	@Override
	public void validateImsLd() {
		// TODO Auto-generated method stub
		
	}

}
