//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for global-propertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="global-propertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}existing"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}global-definition"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.identifier.req"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "global-propertyType", propOrder = {
    "existing",
    "globalDefinition"
})
public class GlobalProperty extends ImeObject implements Serializable
{

    private final static long serialVersionUID = 12345L;
    protected Existing existing;
    @XmlElement(name = "global-definition")
    protected GlobalDefinition globalDefinition;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String identifier;

    /**
     * Gets the value of the existing property.
     * 
     * @return
     *     possible object is
     *     {@link Existing }
     *     
     */
    public Existing getExisting() {
        return existing;
    }

    /**
     * Sets the value of the existing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Existing }
     *     
     */
    public void setExisting(Existing value) {
        this.existing = value;
    }

    /**
     * Gets the value of the globalDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalDefinition }
     *     
     */
    public GlobalDefinition getGlobalDefinition() {
        return globalDefinition;
    }

    /**
     * Sets the value of the globalDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalDefinition }
     *     
     */
    public void setGlobalDefinition(GlobalDefinition value) {
        this.globalDefinition = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

	@Override
	public void validateImsLd() {
		// TODO Auto-generated method stub
		
	}

}
