//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.ByteArrayInputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlInlineBinaryData;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for itemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="itemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}title" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}item" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}metadata" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.identifierref"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.parameters"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.identifier"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.isvisible"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemType", propOrder = {
		"title",
		"itemList",
		"metadata",
		"nameFile",
		"text",
		"link",
		"file"
})
public class Item extends ImeObject
implements Serializable
{

	private final static long serialVersionUID = 12345L;
	protected String title;
	@XmlElement(name = "item")
	protected List<Item> itemList;
	protected Extend metadata;
	@XmlAttribute
	@XmlIDREF
	protected Object identifierref;
	@XmlAttribute
	protected String parameters;
	@XmlAttribute
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	protected String identifier;
	@XmlAttribute
	protected Boolean isvisible;


	@XmlElement(name = "name-file")
	protected String nameFile;

	@XmlInlineBinaryData()
	private byte[] file = null;

	@XmlInlineBinaryData()
	private String link = null;

	@XmlInlineBinaryData()
	private String text = null;

	public String getType() {

		if (text != null && link == null && file == null)
			return "text";
		else if (text == null && link != null && file == null)
			return "link";
		else if (text == null && link == null && file != null)
				return "file";

		return "text";

	}

	public String getNameFile() {
		return nameFile;
	}

	public void setNameFile(String nameFile) {
		this.nameFile = nameFile;
	}

	public byte[] getFile() {
		return file;  
	}

	public void setFile(byte[] file) {
		this.file = file;
	}

	public String getLink() {
		return link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	/**
	 * Gets the value of the title property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the itemList property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the itemList property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getItemList().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Item }
	 * 
	 * 
	 */
	public List<Item> getItemList() {
		if (itemList == null) {
			itemList = new ArrayList<Item>();
		}
		return this.itemList;
	}

	/**
	 * Gets the value of the metadata property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Extend }
	 *     
	 */
	public Extend getMetadata() {
		return metadata;
	}

	/**
	 * Sets the value of the metadata property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Extend }
	 *     
	 */
	public void setMetadata(Extend value) {
		this.metadata = value;
	}

	/**
	 * Gets the value of the identifierref property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Object }
	 *     
	 */
	public Object getIdentifierref() {
		return identifierref;
	}

	/**
	 * Sets the value of the identifierref property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Object }
	 *     
	 */
	public void setIdentifierref(Object value) {
		this.identifierref = value;
	}

	/**
	 * Gets the value of the parameters property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getParameters() {
		return parameters;
	}

	/**
	 * Sets the value of the parameters property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setParameters(String value) {
		this.parameters = value;
	}

	/**
	 * Gets the value of the identifier property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getIdentifier() {
		return identifier;
	}

	/**
	 * Sets the value of the identifier property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setIdentifier(String value) {
		this.identifier = value;
	}

	/**
	 * Gets the value of the isvisible property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Boolean }
	 *     
	 */
	public boolean isIsvisible() {
		if (isvisible == null) {
			return true;
		} else {
			return isvisible;
		}
	}

	/**
	 * Sets the value of the isvisible property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Boolean }
	 *     
	 */
	public void setIsvisible(Boolean value) {
		this.isvisible = value;
	}

	@Override
	public void validateImsLd() { 
		
		clearStructureOfValidationMessages();
		
		if (title == null || title.length() == 0)
		    putWARNING("*Item sem título.");
		
		if ((file == null || file.length == 0) &&
				(text == null || text.length() == 0) &&
				(link== null || link.length() == 0))
			 putWARNING("*Item vazio.");

		if (!isIsvisible())
			putWARNING("*Item '"+title+"' não está visível!");
		
	}

}
