//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;






import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for learning-designType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="learning-designType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}title" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}learning-objectives" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}prerequisites" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}components"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}method"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}metadata" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.level"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.version"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.sequence-used"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.uri.req"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.identifier.req"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "learning-designType", propOrder = {
		"title",
		"learningObjectives",
		"prerequisites",
		"components",
		"method",
		"metadata"
})
public class LearningDesign extends ImeObject   implements Serializable
{ 
	private final static long serialVersionUID = 12345L;
	protected String title;
	@XmlElement(name = "learning-objectives")
	protected ItemModel learningObjectives;
	protected ItemModel prerequisites;
	@XmlElement(required = true)
	protected Components components;
	@XmlElement(required = true)
	protected Method method;
	protected Extend metadata;
	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String level;
	@XmlAttribute
	protected String version;
	@XmlAttribute(name = "sequence-used")
	protected Boolean sequenceUsed;
	@XmlAttribute(required = true)
	protected String uri;
	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	protected String identifier;

	//INCLUSÃO EXTRA
	@XmlAttribute(name = "inherit-roles")
	protected Boolean inheritRoles;

	/**
	 * Gets the value of the title property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the learningObjectives property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link ItemModel }
	 *     
	 */
	public ItemModel getLearningObjectives() {
		return learningObjectives;
	}

	/**
	 * Sets the value of the learningObjectives property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link ItemModel }
	 *     
	 */
	public void setLearningObjectives(ItemModel value) {
		this.learningObjectives = value;
	}

	/**
	 * Gets the value of the prerequisites property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link ItemModel }
	 *     
	 */
	public ItemModel getPrerequisites() {
		return prerequisites;
	}

	/**
	 * Sets the value of the prerequisites property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link ItemModel }
	 *     
	 */
	public void setPrerequisites(ItemModel value) {
		this.prerequisites = value;
	}

	/**
	 * Gets the value of the components property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Components }
	 *     
	 */
	public Components getComponents() {
		return components;
	}

	/**
	 * Sets the value of the components property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Components }
	 *     
	 */
	public void setComponents(Components value) {
		this.components = value;
	}

	/**
	 * Gets the value of the method property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Method }
	 *     
	 */
	public Method getMethod() {
		return method;
	}

	/**
	 * Sets the value of the method property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Method }
	 *     
	 */
	public void setMethod(Method value) {
		this.method = value;
	}

	/**
	 * Gets the value of the metadata property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Extend }
	 *     
	 */
	public Extend getMetadata() {
		return metadata;
	}

	/**
	 * Sets the value of the metadata property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Extend }
	 *     
	 */
	public void setMetadata(Extend value) {
		this.metadata = value;
	}

	/**
	 * Gets the value of the level property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * Sets the value of the level property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setLevel(String value) {
		this.level = value;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setVersion(String value) {
		this.version = value;
	}

	/**
	 * Gets the value of the sequenceUsed property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Boolean }
	 *     
	 */
	public boolean isSequenceUsed() {
		if (sequenceUsed == null) {
			return false;
		} else {
			return sequenceUsed;
		}
	}

	/**
	 * Sets the value of the sequenceUsed property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Boolean }
	 *     
	 */
	public void setSequenceUsed(Boolean value) {
		this.sequenceUsed = value;
	}

	/**
	 * Gets the value of the uri property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getUri() {
		return uri;
	}

	/**
	 * Sets the value of the uri property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setUri(String value) {
		if (value != null && value.length() == 0)
			value = null;

		this.uri = value;
	}

	/**
	 * Gets the value of the identifier property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getIdentifier() {
		return identifier;
	}

	/**
	 * Sets the value of the identifier property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setIdentifier(String value) {
		this.identifier = value;
	}

	public Boolean getInheritRoles() {
		return inheritRoles;
	}

	public void setInheritRoles(Boolean inheritRoles) {
		this.inheritRoles = inheritRoles;
	}


	public void validateImsLd() {
		// OK
		clearStructureOfValidationMessages();

		if (uri == null || uri.length() == 0) {
			uri = null;
			putERROR("*A URI do Modelo Instrucional não foi informada.");
		}
		else if (uri != null && uri.length() > 0) {
			URL u = null;
			try {  
				u = new URL(uri);  
				u.toURI();  
			} 
			catch (Exception e) {  
				putWARNING("*Sintaxe da URI do Modelo Instrucional mal informada.");
			}  
		}

		if (title == null || title.length() == 0)
			putWARNING("*Modelo Instrucional sem título.");


		if (prerequisites != null && prerequisites.isEmpty()) {
			prerequisites = null;
		} else if (prerequisites != null)   {
			prerequisites.validateImsLd();
			putERRORs(prerequisites.getERRORs());
			putWARNINGs(prerequisites.getWARNINGs());
		}
		
		if (learningObjectives != null && learningObjectives.isEmpty()) {
			learningObjectives = null;
		} else if (learningObjectives != null)   {
			learningObjectives.validateImsLd();
			putERRORs(learningObjectives.getERRORs());
			putWARNINGs(learningObjectives.getWARNINGs());
		}

		if (components != null) {
			components.validateImsLd();
			putERRORs(components.getERRORs());
			putWARNINGs(components.getWARNINGs());
		}
		else 
			putERROR("*Não existem componentes definidos...");	


		if (method != null) {
			method.validateImsLd();
			putERRORs(method.getERRORs());
			putWARNINGs(method.getWARNINGs());
		}
		else 
			putERROR("*Não existem métodos definidos...");	





	} 

}
