//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for methodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="methodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}play" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}complete-unit-of-learning" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}on-completion" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}conditions" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "methodType", propOrder = {
    "playList",
    "completeUnitOfLearning",
    "onCompletion",
    "conditionsList"
})
public class Method extends ImeObject
    implements Serializable
{

    private final static long serialVersionUID = 12345L;
    @XmlElement(name = "play", required = true)
    protected List<Play> playList;
    @XmlElement(name = "complete-unit-of-learning")
    protected CompleteUnitOfLearning completeUnitOfLearning;
    @XmlElement(name = "on-completion")
    protected OnCompletion onCompletion;
    @XmlElement(name = "conditions")
    protected List<Conditions> conditionsList;

    /**
     * Gets the value of the playList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the playList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlayList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Play }
     * 
     * 
     */
    public List<Play> getPlayList() {
        if (playList == null) {
            playList = new ArrayList<Play>();
        }
        return this.playList;
    }

    /**
     * Gets the value of the completeUnitOfLearning property.
     * 
     * @return
     *     possible object is
     *     {@link CompleteUnitOfLearning }
     *     
     */
    public CompleteUnitOfLearning getCompleteUnitOfLearning() {
        return completeUnitOfLearning;
    }

    /**
     * Sets the value of the completeUnitOfLearning property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompleteUnitOfLearning }
     *     
     */
    public void setCompleteUnitOfLearning(CompleteUnitOfLearning value) {
        this.completeUnitOfLearning = value;
    }

    /**
     * Gets the value of the onCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link OnCompletion }
     *     
     */
    public OnCompletion getOnCompletion() {
        return onCompletion;
    }

    /**
     * Sets the value of the onCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnCompletion }
     *     
     */
    public void setOnCompletion(OnCompletion value) {
        this.onCompletion = value;
    }

    /**
     * Gets the value of the conditionsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conditionsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConditionsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Conditions }
     * 
     * 
     */
    public List<Conditions> getConditionsList() {
        if (conditionsList == null) {
            conditionsList = new ArrayList<Conditions>();
        }
        return this.conditionsList;
    }

	public void validateImsLd() {
		clearStructureOfValidationMessages();

		if (onCompletion != null) {
			onCompletion.validateImsLd();
			putERRORs(onCompletion.getERRORs());
			putWARNINGs(onCompletion.getWARNINGs());
		}

		if (getPlayList().size() == 0) {
			putERROR("*Nenhum Play Cadastrado...");
		}
		else {
			for (Play play: getPlayList()) {
				play.validateImsLd();
				putERRORs(play.getERRORs());
				putWARNINGs(play.getWARNINGs());
			}
		}
		 
		 
		
	}

}
