//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for notificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="notificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}email-data" maxOccurs="unbounded"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}learning-activity-ref"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}support-activity-ref"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}subject" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "notificationType", propOrder = {
    "emailDataList",
    "learningActivityRef",
    "supportActivityRef",
    "subject"
})
public class Notification extends ImeObject implements Serializable
{

    private final static long serialVersionUID = 12345L;
    @XmlElement(name = "email-data", required = true)
    protected List<EmailData> emailDataList;
    @XmlElement(name = "learning-activity-ref")
    protected LearningActivityRef learningActivityRef;
    @XmlElement(name = "support-activity-ref")
    protected SupportActivityRef supportActivityRef;
    protected String subject;

    /**
     * Gets the value of the emailDataList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emailDataList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmailDataList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmailData }
     * 
     * 
     */
    public List<EmailData> getEmailDataList() {
        if (emailDataList == null) {
            emailDataList = new ArrayList<EmailData>();
        }
        return this.emailDataList;
    }

    /**
     * Gets the value of the learningActivityRef property.
     * 
     * @return
     *     possible object is
     *     {@link LearningActivityRef }
     *     
     */
    public LearningActivityRef getLearningActivityRef() {
        return learningActivityRef;
    }

    /**
     * Sets the value of the learningActivityRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearningActivityRef }
     *     
     */
    public void setLearningActivityRef(LearningActivityRef value) {
        this.learningActivityRef = value;
    }

    /**
     * Gets the value of the supportActivityRef property.
     * 
     * @return
     *     possible object is
     *     {@link SupportActivityRef }
     *     
     */
    public SupportActivityRef getSupportActivityRef() {
        return supportActivityRef;
    }

    /**
     * Sets the value of the supportActivityRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportActivityRef }
     *     
     */
    public void setSupportActivityRef(SupportActivityRef value) {
        this.supportActivityRef = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

	@Override
	public void validateImsLd() {
		// TODO Auto-generated method stub
		
	}

}
