//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.imsglobal.jaxb.ld package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Act_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "act");
    private final static QName _GameService_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "game-service");
    private final static QName _LearningDesign_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "learning-design");
    private final static QName _Service_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "service");
    private final static QName _Method_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "method");
    private final static QName _WhenPropertyValueIsSet_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "when-property-value-is-set");
    private final static QName _LessThan_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "less-than");
    private final static QName _LearningActivity_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "learning-activity");
    private final static QName _Item_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "item");
    private final static QName _Subtract_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "subtract");
    private final static QName _IndexTypeOfElement_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "index-type-of-element");
    private final static QName _ActivityDescription_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "activity-description");
    private final static QName _IndexSearch_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "index-search");
    private final static QName _LocpersProperty_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "locpers-property");
    private final static QName _LearningObject_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "learning-object");
    private final static QName _Play_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "play");
    private final static QName _GreaterThan_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "greater-than");
    private final static QName _Multiply_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "multiply");
    private final static QName _Divide_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "divide");
    private final static QName _CompleteActivity_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "complete-activity");
    private final static QName _Learner_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "learner");
    private final static QName _LearningObjectives_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "learning-objectives");
    private final static QName _GlobProperty_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "glob-property");
    private final static QName _Is_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "is");
    private final static QName _Schemaversion_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "schemaversion");
    private final static QName _SupportActivity_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "support-activity");
    private final static QName _PropertyValue_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "property-value");
    private final static QName _Notification_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "notification");
    private final static QName _GameName_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "game-name");
    private final static QName _Complete_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "complete");
    private final static QName _If_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "if");
    private final static QName _NoValue_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "no-value");
    private final static QName _Staff_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "staff");
    private final static QName _Title_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "title");
    private final static QName _Prerequisites_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "prerequisites");
    private final static QName _Awayreness_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "awayreness");
    private final static QName _EmailData_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "email-data");
    private final static QName _Sum_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "sum");
    private final static QName _GlobpersProperty_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "globpers-property");
    private final static QName _IndexClass_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "index-class");
    private final static QName _Subject_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "subject");
    private final static QName _FeedbackDescription_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "feedback-description");
    private final static QName _InitialValue_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "initial-value");
    private final static QName _PropertyGroup_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "property-group");
    private final static QName _OnCompletion_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "on-completion");
    private final static QName _ChangePropertyValue_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "change-property-value");
    private final static QName _Langstring_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "langstring");
    private final static QName _Components_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "components");
    private final static QName _Then_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "then");
    private final static QName _Roles_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "roles");
    private final static QName _Conditions_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "conditions");
    private final static QName _Not_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "not");
    private final static QName _SendMail_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "send-mail");
    private final static QName _LocProperty_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "loc-property");
    private final static QName _ActivityStructure_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "activity-structure");
    private final static QName _Environment_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "environment");
    private final static QName _UsersInRole_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "users-in-role");
    private final static QName _IsNot_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "is-not");
    private final static QName _And_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "and");
    private final static QName _Environments_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "environments");
    private final static QName _CompleteUnitOfLearning_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "complete-unit-of-learning");
    private final static QName _Properties_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "properties");
    private final static QName _Or_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "or");
    private final static QName _Else_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "else");
    private final static QName _Information_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "information");
    private final static QName _Index_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "index");
    private final static QName _Monitor_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "monitor");
    private final static QName _Conference_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "conference");
    private final static QName _RolePart_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "role-part");
    private final static QName _Metadata_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "metadata");
    private final static QName _WhenConditionTrue_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "when-condition-true");
    private final static QName _Activities_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "activities");
    private final static QName _Hide_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "hide");
    private final static QName _CompletePlay_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "complete-play");
    private final static QName _Schema_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "schema");
    private final static QName _CompleteAct_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "complete-act");
    private final static QName _Show_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "show");
    private final static QName _Calculate_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "calculate");
    private final static QName _Tool_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "tool");
    private final static QName _Expression_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "expression");
    private final static QName _LocroleProperty_QNAME = new QName("http://www.imsglobal.org/xsd/imsld_v1p0", "locrole-property");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.imsglobal.jaxb.ld
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SupportActivityRef }
     * 
     */
    public SupportActivityRef createSupportActivityRef() {
        return new SupportActivityRef();
    }

    /**
     * Create an instance of {@link CompleteUnitOfLearning }
     * 
     */
    public CompleteUnitOfLearning createCompleteUnitOfLearning() {
        return new CompleteUnitOfLearning();
    }

    /**
     * Create an instance of {@link Participant }
     * 
     */
    public Participant createParticipant() {
        return new Participant();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link SendMail }
     * 
     */
    public SendMail createSendMail() {
        return new SendMail();
    }

    /**
     * Create an instance of {@link IsMemberOfRole }
     * 
     */
    public IsMemberOfRole createIsMemberOfRole() {
        return new IsMemberOfRole();
    }

    /**
     * Create an instance of {@link IndexSearch }
     * 
     */
    public IndexSearch createIndexSearch() {
        return new IndexSearch();
    }

    /**
     * Create an instance of {@link EmailData }
     * 
     */
    public EmailData createEmailData() {
        return new EmailData();
    }

    /**
     * Create an instance of {@link UsersInRole }
     * 
     */
    public UsersInRole createUsersInRole() {
        return new UsersInRole();
    }

    /**
     * Create an instance of {@link TimeLimit }
     * 
     */
    public TimeLimit createTimeLimit() {
        return new TimeLimit();
    }

    /**
     * Create an instance of {@link Environments }
     * 
     */
    public Environments createEnvironments() {
        return new Environments();
    }

    /**
     * Create an instance of {@link RolePart }
     * 
     */
    public RolePart createRolePart() {
        return new RolePart();
    }

    /**
     * Create an instance of {@link ItemModel }
     * 
     */
    public ItemModel createItemModel() {
        return new ItemModel();
    }

    /**
     * Create an instance of {@link GlobalDefinition }
     * 
     */
    public GlobalDefinition createGlobalDefinition() {
        return new GlobalDefinition();
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link PropertyGroup }
     * 
     */
    public PropertyGroup createPropertyGroup() {
        return new PropertyGroup();
    }

    /**
     * Create an instance of {@link Roles }
     * 
     */
    public Roles createRoles() {
        return new Roles();
    }

    /**
     * Create an instance of {@link WhenRolePartCompleted }
     * 
     */
    public WhenRolePartCompleted createWhenRolePartCompleted() {
        return new WhenRolePartCompleted();
    }

    /**
     * Create an instance of {@link RoleProperty }
     * 
     */
    public RoleProperty createRoleProperty() {
        return new RoleProperty();
    }

    /**
     * Create an instance of {@link Learner }
     * 
     */
    public Learner createLearner() {
        return new Learner();
    }

    /**
     * Create an instance of {@link NoValue }
     * 
     */
    public NoValue createNoValue() {
        return new NoValue();
    }

    /**
     * Create an instance of {@link Environment }
     * 
     */
    public Environment createEnvironment() {
        return new Environment();
    }

    /**
     * Create an instance of {@link PropertyRef }
     * 
     */
    public PropertyRef createPropertyRef() {
        return new PropertyRef();
    }

    /**
     * Create an instance of {@link CompleteAct }
     * 
     */
    public CompleteAct createCompleteAct() {
        return new CompleteAct();
    }

    /**
     * Create an instance of {@link Act }
     * 
     */
    public Act createAct() {
        return new Act();
    }

    /**
     * Create an instance of {@link LearningActivity }
     * 
     */
    public LearningActivity createLearningActivity() {
        return new LearningActivity();
    }

    /**
     * Create an instance of {@link GameService }
     * 
     */
    public GameService createGameService() {
        return new GameService();
    }

    /**
     * Create an instance of {@link LearningDesign }
     * 
     */
    public LearningDesign createLearningDesign() {
        return new LearningDesign();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Play }
     * 
     */
    public Play createPlay() {
        return new Play();
    }

    /**
     * Create an instance of {@link WhenPropertyValueIsSet }
     * 
     */
    public WhenPropertyValueIsSet createWhenPropertyValueIsSet() {
        return new WhenPropertyValueIsSet();
    }

    /**
     * Create an instance of {@link Observer }
     * 
     */
    public Observer createObserver() {
        return new Observer();
    }

    /**
     * Create an instance of {@link ShowHide }
     * 
     */
    public ShowHide createShowHide() {
        return new ShowHide();
    }

    /**
     * Create an instance of {@link Awayreness }
     * 
     */
    public Awayreness createAwayreness() {
        return new Awayreness();
    }

    /**
     * Create an instance of {@link GlobalProperty }
     * 
     */
    public GlobalProperty createGlobalProperty() {
        return new GlobalProperty();
    }

    /**
     * Create an instance of {@link CompletePlay }
     * 
     */
    public CompletePlay createCompletePlay() {
        return new CompletePlay();
    }

    /**
     * Create an instance of {@link UnitOfLearningHref }
     * 
     */
    public UnitOfLearningHref createUnitOfLearningHref() {
        return new UnitOfLearningHref();
    }

    /**
     * Create an instance of {@link DatetimeActivityStarted }
     * 
     */
    public DatetimeActivityStarted createDatetimeActivityStarted() {
        return new DatetimeActivityStarted();
    }

    /**
     * Create an instance of {@link WhenConditionTrue }
     * 
     */
    public WhenConditionTrue createWhenConditionTrue() {
        return new WhenConditionTrue();
    }

    /**
     * Create an instance of {@link PlayRef }
     * 
     */
    public PlayRef createPlayRef() {
        return new PlayRef();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link ActivityStructureRef }
     * 
     */
    public ActivityStructureRef createActivityStructureRef() {
        return new ActivityStructureRef();
    }

    /**
     * Create an instance of {@link OnCompletion }
     * 
     */
    public OnCompletion createOnCompletion() {
        return new OnCompletion();
    }

    /**
     * Create an instance of {@link PropertyValue }
     * 
     */
    public PropertyValue createPropertyValue() {
        return new PropertyValue();
    }

    /**
     * Create an instance of {@link CompleteActivity }
     * 
     */
    public CompleteActivity createCompleteActivity() {
        return new CompleteActivity();
    }

    /**
     * Create an instance of {@link Expression }
     * 
     */
    public Expression createExpression() {
        return new Expression();
    }

    /**
     * Create an instance of {@link TimeUnitOfLearningStarted }
     * 
     */
    public TimeUnitOfLearningStarted createTimeUnitOfLearningStarted() {
        return new TimeUnitOfLearningStarted();
    }

    /**
     * Create an instance of {@link SupportActivity }
     * 
     */
    public SupportActivity createSupportActivity() {
        return new SupportActivity();
    }

    /**
     * Create an instance of {@link LearningActivityRef }
     * 
     */
    public LearningActivityRef createLearningActivityRef() {
        return new LearningActivityRef();
    }

    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link WhenPlayCompleted }
     * 
     */
    public WhenPlayCompleted createWhenPlayCompleted() {
        return new WhenPlayCompleted();
    }

    /**
     * Create an instance of {@link Method }
     * 
     */
    public Method createMethod() {
        return new Method();
    }

    /**
     * Create an instance of {@link ConferenceManager }
     * 
     */
    public ConferenceManager createConferenceManager() {
        return new ConferenceManager();
    }

    /**
     * Create an instance of {@link Datatype }
     * 
     */
    public Datatype createDatatype() {
        return new Datatype();
    }

    /**
     * Create an instance of {@link Calculate }
     * 
     */
    public Calculate createCalculate() {
        return new Calculate();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Staff }
     * 
     */
    public Staff createStaff() {
        return new Staff();
    }

    /**
     * Create an instance of {@link Sum }
     * 
     */
    public Sum createSum() {
        return new Sum();
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link Extend }
     * 
     */
    public Extend createExtend() {
        return new Extend();
    }

    /**
     * Create an instance of {@link Else }
     * 
     */
    public Else createElse() {
        return new Else();
    }

    /**
     * Create an instance of {@link Index }
     * 
     */
    public Index createIndex() {
        return new Index();
    }

    /**
     * Create an instance of {@link ActivityStructure }
     * 
     */
    public ActivityStructure createActivityStructure() {
        return new ActivityStructure();
    }

    /**
     * Create an instance of {@link Conference }
     * 
     */
    public Conference createConference() {
        return new Conference();
    }

    /**
     * Create an instance of {@link Operator }
     * 
     */
    public Operator createOperator() {
        return new Operator();
    }

    /**
     * Create an instance of {@link IndexElement }
     * 
     */
    public IndexElement createIndexElement() {
        return new IndexElement();
    }

    /**
     * Create an instance of {@link RoleRef }
     * 
     */
    public RoleRef createRoleRef() {
        return new RoleRef();
    }

    /**
     * Create an instance of {@link WhenLastActCompleted }
     * 
     */
    public WhenLastActCompleted createWhenLastActCompleted() {
        return new WhenLastActCompleted();
    }

    /**
     * Create an instance of {@link Activities }
     * 
     */
    public Activities createActivities() {
        return new Activities();
    }

    /**
     * Create an instance of {@link Complete }
     * 
     */
    public Complete createComplete() {
        return new Complete();
    }

    /**
     * Create an instance of {@link EnvironmentRef }
     * 
     */
    public EnvironmentRef createEnvironmentRef() {
        return new EnvironmentRef();
    }

    /**
     * Create an instance of {@link Existing }
     * 
     */
    public Existing createExisting() {
        return new Existing();
    }

    /**
     * Create an instance of {@link Restriction }
     * 
     */
    public Restriction createRestriction() {
        return new Restriction();
    }

    /**
     * Create an instance of {@link ItemRef }
     * 
     */
    public ItemRef createItemRef() {
        return new ItemRef();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link RolePartRef }
     * 
     */
    public RolePartRef createRolePartRef() {
        return new RolePartRef();
    }

    /**
     * Create an instance of {@link CurrentDatetime }
     * 
     */
    public CurrentDatetime createCurrentDatetime() {
        return new CurrentDatetime();
    }

    /**
     * Create an instance of {@link Monitor }
     * 
     */
    public Monitor createMonitor() {
        return new Monitor();
    }

    /**
     * Create an instance of {@link Then }
     * 
     */
    public Then createThen() {
        return new Then();
    }

    /**
     * Create an instance of {@link ActRef }
     * 
     */
    public ActRef createActRef() {
        return new ActRef();
    }

    /**
     * Create an instance of {@link LearningObject }
     * 
     */
    public LearningObject createLearningObject() {
        return new LearningObject();
    }

    /**
     * Create an instance of {@link Self }
     * 
     */
    public Self createSelf() {
        return new Self();
    }

    /**
     * Create an instance of {@link Moderator }
     * 
     */
    public Moderator createModerator() {
        return new Moderator();
    }

    /**
     * Create an instance of {@link PropertyGroupRef }
     * 
     */
    public PropertyGroupRef createPropertyGroupRef() {
        return new PropertyGroupRef();
    }

    /**
     * Create an instance of {@link UserChoice }
     * 
     */
    public UserChoice createUserChoice() {
        return new UserChoice();
    }

    /**
     * Create an instance of {@link ChangePropertyValue }
     * 
     */
    public ChangePropertyValue createChangePropertyValue() {
        return new ChangePropertyValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Act }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "act")
    public JAXBElement<Act> createAct(Act value) {
        return new JAXBElement<Act>(_Act_QNAME, Act.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GameService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "game-service")
    public JAXBElement<GameService> createGameService(GameService value) {
        return new JAXBElement<GameService>(_GameService_QNAME, GameService.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LearningDesign }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "learning-design")
    public JAXBElement<LearningDesign> createLearningDesign(LearningDesign value) {
        return new JAXBElement<LearningDesign>(_LearningDesign_QNAME, LearningDesign.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Service }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "service")
    public JAXBElement<Service> createService(Service value) {
        return new JAXBElement<Service>(_Service_QNAME, Service.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Method }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "method")
    public JAXBElement<Method> createMethod(Method value) {
        return new JAXBElement<Method>(_Method_QNAME, Method.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WhenPropertyValueIsSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "when-property-value-is-set")
    public JAXBElement<WhenPropertyValueIsSet> createWhenPropertyValueIsSet(WhenPropertyValueIsSet value) {
        return new JAXBElement<WhenPropertyValueIsSet>(_WhenPropertyValueIsSet_QNAME, WhenPropertyValueIsSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Calculate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "less-than")
    public JAXBElement<Calculate> createLessThan(Calculate value) {
        return new JAXBElement<Calculate>(_LessThan_QNAME, Calculate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LearningActivity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "learning-activity")
    public JAXBElement<LearningActivity> createLearningActivity(LearningActivity value) {
        return new JAXBElement<LearningActivity>(_LearningActivity_QNAME, LearningActivity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Item }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "item")
    public JAXBElement<Item> createItem(Item value) {
        return new JAXBElement<Item>(_Item_QNAME, Item.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Calculate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "subtract")
    public JAXBElement<Calculate> createSubtract(Calculate value) {
        return new JAXBElement<Calculate>(_Subtract_QNAME, Calculate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "index-type-of-element")
    public JAXBElement<String> createIndexTypeOfElement(String value) {
        return new JAXBElement<String>(_IndexTypeOfElement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "activity-description")
    public JAXBElement<ItemModel> createActivityDescription(ItemModel value) {
        return new JAXBElement<ItemModel>(_ActivityDescription_QNAME, ItemModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexSearch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "index-search")
    public JAXBElement<IndexSearch> createIndexSearch(IndexSearch value) {
        return new JAXBElement<IndexSearch>(_IndexSearch_QNAME, IndexSearch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Property }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "locpers-property")
    public JAXBElement<Property> createLocpersProperty(Property value) {
        return new JAXBElement<Property>(_LocpersProperty_QNAME, Property.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LearningObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "learning-object")
    public JAXBElement<LearningObject> createLearningObject(LearningObject value) {
        return new JAXBElement<LearningObject>(_LearningObject_QNAME, LearningObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Play }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "play")
    public JAXBElement<Play> createPlay(Play value) {
        return new JAXBElement<Play>(_Play_QNAME, Play.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Calculate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "greater-than")
    public JAXBElement<Calculate> createGreaterThan(Calculate value) {
        return new JAXBElement<Calculate>(_GreaterThan_QNAME, Calculate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Calculate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "multiply")
    public JAXBElement<Calculate> createMultiply(Calculate value) {
        return new JAXBElement<Calculate>(_Multiply_QNAME, Calculate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Calculate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "divide")
    public JAXBElement<Calculate> createDivide(Calculate value) {
        return new JAXBElement<Calculate>(_Divide_QNAME, Calculate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteActivity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "complete-activity")
    public JAXBElement<CompleteActivity> createCompleteActivity(CompleteActivity value) {
        return new JAXBElement<CompleteActivity>(_CompleteActivity_QNAME, CompleteActivity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Learner }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "learner")
    public JAXBElement<Learner> createLearner(Learner value) {
        return new JAXBElement<Learner>(_Learner_QNAME, Learner.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "learning-objectives")
    public JAXBElement<ItemModel> createLearningObjectives(ItemModel value) {
        return new JAXBElement<ItemModel>(_LearningObjectives_QNAME, ItemModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GlobalProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "glob-property")
    public JAXBElement<GlobalProperty> createGlobProperty(GlobalProperty value) {
        return new JAXBElement<GlobalProperty>(_GlobProperty_QNAME, GlobalProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Calculate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "is")
    public JAXBElement<Calculate> createIs(Calculate value) {
        return new JAXBElement<Calculate>(_Is_QNAME, Calculate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "schemaversion")
    public JAXBElement<String> createSchemaversion(String value) {
        return new JAXBElement<String>(_Schemaversion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SupportActivity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "support-activity")
    public JAXBElement<SupportActivity> createSupportActivity(SupportActivity value) {
        return new JAXBElement<SupportActivity>(_SupportActivity_QNAME, SupportActivity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "property-value")
    public JAXBElement<PropertyValue> createPropertyValue(PropertyValue value) {
        return new JAXBElement<PropertyValue>(_PropertyValue_QNAME, PropertyValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Notification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "notification")
    public JAXBElement<Notification> createNotification(Notification value) {
        return new JAXBElement<Notification>(_Notification_QNAME, Notification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "game-name")
    public JAXBElement<String> createGameName(String value) {
        return new JAXBElement<String>(_GameName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Complete }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "complete")
    public JAXBElement<Complete> createComplete(Complete value) {
        return new JAXBElement<Complete>(_Complete_QNAME, Complete.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Expression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "if")
    public JAXBElement<Expression> createIf(Expression value) {
        return new JAXBElement<Expression>(_If_QNAME, Expression.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "no-value")
    public JAXBElement<NoValue> createNoValue(NoValue value) {
        return new JAXBElement<NoValue>(_NoValue_QNAME, NoValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Staff }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "staff")
    public JAXBElement<Staff> createStaff(Staff value) {
        return new JAXBElement<Staff>(_Staff_QNAME, Staff.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "prerequisites")
    public JAXBElement<ItemModel> createPrerequisites(ItemModel value) {
        return new JAXBElement<ItemModel>(_Prerequisites_QNAME, ItemModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Awayreness }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "awayreness")
    public JAXBElement<Awayreness> createAwayreness(Awayreness value) {
        return new JAXBElement<Awayreness>(_Awayreness_QNAME, Awayreness.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmailData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "email-data")
    public JAXBElement<EmailData> createEmailData(EmailData value) {
        return new JAXBElement<EmailData>(_EmailData_QNAME, EmailData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "sum")
    public JAXBElement<Sum> createSum(Sum value) {
        return new JAXBElement<Sum>(_Sum_QNAME, Sum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GlobalProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "globpers-property")
    public JAXBElement<GlobalProperty> createGlobpersProperty(GlobalProperty value) {
        return new JAXBElement<GlobalProperty>(_GlobpersProperty_QNAME, GlobalProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "index-class")
    public JAXBElement<String> createIndexClass(String value) {
        return new JAXBElement<String>(_IndexClass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "subject")
    public JAXBElement<String> createSubject(String value) {
        return new JAXBElement<String>(_Subject_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "feedback-description")
    public JAXBElement<ItemModel> createFeedbackDescription(ItemModel value) {
        return new JAXBElement<ItemModel>(_FeedbackDescription_QNAME, ItemModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "initial-value")
    public JAXBElement<String> createInitialValue(String value) {
        return new JAXBElement<String>(_InitialValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "property-group")
    public JAXBElement<PropertyGroup> createPropertyGroup(PropertyGroup value) {
        return new JAXBElement<PropertyGroup>(_PropertyGroup_QNAME, PropertyGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OnCompletion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "on-completion")
    public JAXBElement<OnCompletion> createOnCompletion(OnCompletion value) {
        return new JAXBElement<OnCompletion>(_OnCompletion_QNAME, OnCompletion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangePropertyValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "change-property-value")
    public JAXBElement<ChangePropertyValue> createChangePropertyValue(ChangePropertyValue value) {
        return new JAXBElement<ChangePropertyValue>(_ChangePropertyValue_QNAME, ChangePropertyValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "langstring")
    public JAXBElement<String> createLangstring(String value) {
        return new JAXBElement<String>(_Langstring_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Components }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "components")
    public JAXBElement<Components> createComponents(Components value) {
        return new JAXBElement<Components>(_Components_QNAME, Components.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Then }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "then")
    public JAXBElement<Then> createThen(Then value) {
        return new JAXBElement<Then>(_Then_QNAME, Then.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Roles }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "roles")
    public JAXBElement<Roles> createRoles(Roles value) {
        return new JAXBElement<Roles>(_Roles_QNAME, Roles.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Conditions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "conditions")
    public JAXBElement<Conditions> createConditions(Conditions value) {
        return new JAXBElement<Conditions>(_Conditions_QNAME, Conditions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Expression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "not")
    public JAXBElement<Expression> createNot(Expression value) {
        return new JAXBElement<Expression>(_Not_QNAME, Expression.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendMail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "send-mail")
    public JAXBElement<SendMail> createSendMail(SendMail value) {
        return new JAXBElement<SendMail>(_SendMail_QNAME, SendMail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Property }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "loc-property")
    public JAXBElement<Property> createLocProperty(Property value) {
        return new JAXBElement<Property>(_LocProperty_QNAME, Property.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivityStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "activity-structure")
    public JAXBElement<ActivityStructure> createActivityStructure(ActivityStructure value) {
        return new JAXBElement<ActivityStructure>(_ActivityStructure_QNAME, ActivityStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Environment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "environment")
    public JAXBElement<Environment> createEnvironment(Environment value) {
        return new JAXBElement<Environment>(_Environment_QNAME, Environment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsersInRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "users-in-role")
    public JAXBElement<UsersInRole> createUsersInRole(UsersInRole value) {
        return new JAXBElement<UsersInRole>(_UsersInRole_QNAME, UsersInRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Calculate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "is-not")
    public JAXBElement<Calculate> createIsNot(Calculate value) {
        return new JAXBElement<Calculate>(_IsNot_QNAME, Calculate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Operator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "and")
    public JAXBElement<Operator> createAnd(Operator value) {
        return new JAXBElement<Operator>(_And_QNAME, Operator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Environments }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "environments")
    public JAXBElement<Environments> createEnvironments(Environments value) {
        return new JAXBElement<Environments>(_Environments_QNAME, Environments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteUnitOfLearning }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "complete-unit-of-learning")
    public JAXBElement<CompleteUnitOfLearning> createCompleteUnitOfLearning(CompleteUnitOfLearning value) {
        return new JAXBElement<CompleteUnitOfLearning>(_CompleteUnitOfLearning_QNAME, CompleteUnitOfLearning.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Properties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "properties")
    public JAXBElement<Properties> createProperties(Properties value) {
        return new JAXBElement<Properties>(_Properties_QNAME, Properties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Operator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "or")
    public JAXBElement<Operator> createOr(Operator value) {
        return new JAXBElement<Operator>(_Or_QNAME, Operator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Else }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "else")
    public JAXBElement<Else> createElse(Else value) {
        return new JAXBElement<Else>(_Else_QNAME, Else.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "information")
    public JAXBElement<ItemModel> createInformation(ItemModel value) {
        return new JAXBElement<ItemModel>(_Information_QNAME, ItemModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Index }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "index")
    public JAXBElement<Index> createIndex(Index value) {
        return new JAXBElement<Index>(_Index_QNAME, Index.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Monitor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "monitor")
    public JAXBElement<Monitor> createMonitor(Monitor value) {
        return new JAXBElement<Monitor>(_Monitor_QNAME, Monitor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Conference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "conference")
    public JAXBElement<Conference> createConference(Conference value) {
        return new JAXBElement<Conference>(_Conference_QNAME, Conference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RolePart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "role-part")
    public JAXBElement<RolePart> createRolePart(RolePart value) {
        return new JAXBElement<RolePart>(_RolePart_QNAME, RolePart.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Extend }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "metadata")
    public JAXBElement<Extend> createMetadata(Extend value) {
        return new JAXBElement<Extend>(_Metadata_QNAME, Extend.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WhenConditionTrue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "when-condition-true")
    public JAXBElement<WhenConditionTrue> createWhenConditionTrue(WhenConditionTrue value) {
        return new JAXBElement<WhenConditionTrue>(_WhenConditionTrue_QNAME, WhenConditionTrue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Activities }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "activities")
    public JAXBElement<Activities> createActivities(Activities value) {
        return new JAXBElement<Activities>(_Activities_QNAME, Activities.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowHide }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "hide")
    public JAXBElement<ShowHide> createHide(ShowHide value) {
        return new JAXBElement<ShowHide>(_Hide_QNAME, ShowHide.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompletePlay }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "complete-play")
    public JAXBElement<CompletePlay> createCompletePlay(CompletePlay value) {
        return new JAXBElement<CompletePlay>(_CompletePlay_QNAME, CompletePlay.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "schema")
    public JAXBElement<String> createSchema(String value) {
        return new JAXBElement<String>(_Schema_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteAct }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "complete-act")
    public JAXBElement<CompleteAct> createCompleteAct(CompleteAct value) {
        return new JAXBElement<CompleteAct>(_CompleteAct_QNAME, CompleteAct.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowHide }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "show")
    public JAXBElement<ShowHide> createShow(ShowHide value) {
        return new JAXBElement<ShowHide>(_Show_QNAME, ShowHide.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Expression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "calculate")
    public JAXBElement<Expression> createCalculate(Expression value) {
        return new JAXBElement<Expression>(_Calculate_QNAME, Expression.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "tool")
    public JAXBElement<String> createTool(String value) {
        return new JAXBElement<String>(_Tool_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Expression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "expression")
    public JAXBElement<Expression> createExpression(Expression value) {
        return new JAXBElement<Expression>(_Expression_QNAME, Expression.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoleProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", name = "locrole-property")
    public JAXBElement<RoleProperty> createLocroleProperty(RoleProperty value) {
        return new JAXBElement<RoleProperty>(_LocroleProperty_QNAME, RoleProperty.class, null, value);
    }

}
