//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for on-completionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="on-completionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}feedback-description" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}change-property-value" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}notification" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "on-completionType", propOrder = {
    "feedbackDescription",
    "changePropertyValue",
    "notification"
})
public class OnCompletion extends ImeObject
    implements Serializable
{

    private final static long serialVersionUID = 12345L;
    @XmlElement(name = "feedback-description")
    protected ItemModel feedbackDescription;
    @XmlElement(name = "change-property-value")
    protected List<ChangePropertyValue> changePropertyValue;
    protected List<Notification> notification;

    /**
     * Gets the value of the feedbackDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ItemModel }
     *     
     */
    public ItemModel getFeedbackDescription() {
        return feedbackDescription;
    }

    /**
     * Sets the value of the feedbackDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemModel }
     *     
     */
    public void setFeedbackDescription(ItemModel value) {
        this.feedbackDescription = value;
    }

    /**
     * Gets the value of the changePropertyValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changePropertyValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChangePropertyValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChangePropertyValue }
     * 
     * 
     */
    public List<ChangePropertyValue> getChangePropertyValue() {
        if (changePropertyValue == null) {
            changePropertyValue = new ArrayList<ChangePropertyValue>();
        }
        return this.changePropertyValue;
    }

    /**
     * Gets the value of the notification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Notification }
     * 
     * 
     */
    public List<Notification> getNotification() {
        if (notification == null) {
            notification = new ArrayList<Notification>();
        }
        return this.notification;
    }

	@Override
	public void validateImsLd() {  
		clearStructureOfValidationMessages(); 

		if (feedbackDescription != null && feedbackDescription.isEmpty()) {
			feedbackDescription = null;
		} else if (feedbackDescription != null) {
			feedbackDescription.validateImsLd();
			putERRORs(feedbackDescription.getERRORs());
			putWARNINGs(feedbackDescription.getWARNINGs());
		}
		
		
	}

}
