//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//

@XmlSchema(
		namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, 
		xmlns={ @XmlNs(prefix="imscp", namespaceURI="http://www.imsglobal.org/xsd/imscp_v1p1"),
				@XmlNs(prefix="imsld", namespaceURI="http://www.imsglobal.org/xsd/imsld_v1p0"),
		})
package org.imsglobal.jaxb.ld;
import javax.xml.bind.annotation.*;

