//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for propertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="propertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}loc-property"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}locpers-property"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}locrole-property"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}globpers-property"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}glob-property"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}property-group"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propertiesType", propOrder = {
    "locPropertyOrLocpersPropertyOrLocroleProperty"
})
public class Properties extends ImeObject
    implements Serializable
{

    private final static long serialVersionUID = 12345L;
    @XmlElementRefs({
        @XmlElementRef(name = "loc-property", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "globpers-property", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "locpers-property", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "glob-property", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "locrole-property", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class),
        @XmlElementRef(name = "property-group", namespace = "http://www.imsglobal.org/xsd/imsld_v1p0", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> locPropertyOrLocpersPropertyOrLocroleProperty;

    /**
     * Gets the value of the locPropertyOrLocpersPropertyOrLocroleProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locPropertyOrLocpersPropertyOrLocroleProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocPropertyOrLocpersPropertyOrLocroleProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link RoleProperty }{@code >}
     * {@link JAXBElement }{@code <}{@link Property }{@code >}
     * {@link JAXBElement }{@code <}{@link PropertyGroup }{@code >}
     * {@link JAXBElement }{@code <}{@link GlobalProperty }{@code >}
     * {@link JAXBElement }{@code <}{@link Property }{@code >}
     * {@link JAXBElement }{@code <}{@link GlobalProperty }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getLocPropertyOrLocpersPropertyOrLocroleProperty() {
        if (locPropertyOrLocpersPropertyOrLocroleProperty == null) {
            locPropertyOrLocpersPropertyOrLocroleProperty = new ArrayList<JAXBElement<?>>();
        }
        return this.locPropertyOrLocpersPropertyOrLocroleProperty;
    }

	@Override
	public void validateImsLd() {
		// TODO Auto-generated method stub
		
	}

}
