//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 10:43:46 AM BRST 
//


package org.imsglobal.jaxb.ld;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import br.edu.ifg.ime.ld.ImeObject;


/**
 * <p>Java class for support-activityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="support-activityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}title" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}role-ref" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}environment-ref" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}activity-description"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}complete-activity" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}on-completion" minOccurs="0"/>
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsld_v1p0}metadata" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.parameters"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.identifier.req"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsld_v1p0}attr.isvisible"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "support-activityType", propOrder = {
    "title",
    "roleRefList",
    "environmentRefList",
    "activityDescription",
    "completeActivity",
    "onCompletion",
    "metadata"
})
public class SupportActivity extends ImeObject implements Serializable
{

    private final static long serialVersionUID = 12345L;
    protected String title;
    @XmlElement(name = "role-ref")
    protected List<RoleRef> roleRefList;
    @XmlElement(name = "environment-ref")
    protected List<EnvironmentRef> environmentRefList;
    @XmlElement(name = "activity-description", required = true)
    protected ItemModel activityDescription;
    @XmlElement(name = "complete-activity")
    protected CompleteActivity completeActivity;
    @XmlElement(name = "on-completion")
    protected OnCompletion onCompletion;
    protected Extend metadata;
    @XmlAttribute
    protected String parameters;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String identifier;
    @XmlAttribute
    protected Boolean isvisible;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the roleRefList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleRefList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleRefList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoleRef }
     * 
     * 
     */
    public List<RoleRef> getRoleRefList() {
        if (roleRefList == null) {
            roleRefList = new ArrayList<RoleRef>();
        }
        return this.roleRefList;
    }

    /**
     * Gets the value of the environmentRefList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the environmentRefList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnvironmentRefList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnvironmentRef }
     * 
     * 
     */
    public List<EnvironmentRef> getEnvironmentRefList() {
        if (environmentRefList == null) {
            environmentRefList = new ArrayList<EnvironmentRef>();
        }
        return this.environmentRefList;
    }

    /**
     * Gets the value of the activityDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ItemModel }
     *     
     */
    public ItemModel getActivityDescription() {
        return activityDescription;
    }

    /**
     * Sets the value of the activityDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemModel }
     *     
     */
    public void setActivityDescription(ItemModel value) {
        this.activityDescription = value;
    }

    /**
     * Gets the value of the completeActivity property.
     * 
     * @return
     *     possible object is
     *     {@link CompleteActivity }
     *     
     */
    public CompleteActivity getCompleteActivity() {
        return completeActivity;
    }

    /**
     * Sets the value of the completeActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompleteActivity }
     *     
     */
    public void setCompleteActivity(CompleteActivity value) {
        this.completeActivity = value;
    }

    /**
     * Gets the value of the onCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link OnCompletion }
     *     
     */
    public OnCompletion getOnCompletion() {
        return onCompletion;
    }

    /**
     * Sets the value of the onCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnCompletion }
     *     
     */
    public void setOnCompletion(OnCompletion value) {
        this.onCompletion = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Extend }
     *     
     */
    public Extend getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extend }
     *     
     */
    public void setMetadata(Extend value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameters(String value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the isvisible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsvisible() {
        if (isvisible == null) {
            return true;
        } else {
            return isvisible;
        }
    }

    /**
     * Sets the value of the isvisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsvisible(Boolean value) {
        this.isvisible = value;
    }

	@Override
	public void validateImsLd() {

		clearStructureOfValidationMessages();

		if (title == null || title.length() == 0)
			putWARNING("*Atividade sem título!");
		
		if (!isIsvisible())
			putWARNING("*Atividade: "+title+" não está visível!");
		

		if (activityDescription == null || (activityDescription != null && activityDescription.isEmpty())) {
			activityDescription = null;
			putERROR("*A descrição da atividade deve ser preenchida com ao menos um item.");
		} else if (activityDescription != null) {
			activityDescription.validateImsLd();
			putERRORs(activityDescription.getERRORs());
			putWARNINGs(activityDescription.getWARNINGs());
		}

	}

}
